/* Run with: SUPABASE_SERVICE_ROLE_KEY=... node scripts/seed-demo.mjs
   Never expose this key to the browser. This only removes records explicitly marked is_demo. */
import { createClient } from '@supabase/supabase-js';
const url=process.env.NEXT_PUBLIC_SUPABASE_URL; const key=process.env.SUPABASE_SERVICE_ROLE_KEY;
if(!url||!key) throw new Error('NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required.');
const db=createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}});
const accounts=[['Central Authority Demo','central@gramswasthya.demo','central_authority'],['PHC Head Demo','phchead@gramswasthya.demo','phc_head'],['ASHA Worker Demo','worker@gramswasthya.demo','phc_worker'],['Patient Demo','patient@gramswasthya.demo','patient']];
async function userFor(email){let page=1;for(;;){const {data,error}=await db.auth.admin.listUsers({page,perPage:1000});if(error)throw error;const found=data.users.find(u=>u.email===email);if(found)return found;if(data.users.length<1000)break;page++}const {data,error}=await db.auth.admin.createUser({email,password:'Demo@12345',email_confirm:true});if(error)throw error;return data.user}
const users={};for(const [name,email,role] of accounts){const user=await userFor(email);users[role]=user.id;const {error}=await db.from('users').upsert({id:user.id,name,email,role},{onConflict:'id'});if(error)throw error}
const {data:old}=await db.from('patients').select('id').eq('is_demo',true);if(old?.length){const ids=old.map(x=>x.id);for(const table of ['clinical_records','correction_requests','record_audit_history','patient_accounts']){const {error}=await db.from(table).delete().in('patient_id',ids);if(error)throw error}const {error}=await db.from('patients').delete().in('id',ids);if(error)throw error}
const phcId='d0000000-0000-0000-0000-000000000001',patientId='d0000000-0000-0000-0000-000000000002';let out=await db.from('facilities').upsert({id:phcId,name:'Demo Primary Health Centre',code:'PHC-DEMO-001',area:'Demo Area',village:'Demo Village',status:'active'},{onConflict:'id'});if(out.error)throw out.error;for(const role of ['phc_head','phc_worker']){const {error}=await db.from('users').update({facility_id:phcId}).eq('id',users[role]);if(error)throw error}
out=await db.from('patients').upsert({id:patientId,patient_code:'GS-DEMO-001',is_demo:true,name:'Demo Patient',age:28,gender:'female',village:'Demo Village',district:'Demo Area',phone:'+91 90000 00001',blood_group:'B+',existing_conditions:['No major known medical history'],allergies:['None reported'],registered_phc_id:phcId,registered_by:users.phc_worker,verification_status:'verified',verified_by:users.phc_worker,verified_at:'2026-09-18T09:00:00Z'},{onConflict:'id'});if(out.error)throw out.error;out=await db.from('patient_accounts').upsert({user_id:users.patient,patient_id:patientId},{onConflict:'user_id'});if(out.error)throw out.error;
const records=[{record_kind:'historical',occurred_on:'2025-06-15',title:'General Health Check',description:'Routine health check recorded by PHC.',structured_data:{encounter_type:'general_health_check'},verified_at:'2025-06-15T10:00:00Z'},{record_kind:'current',occurred_on:'2026-09-18',title:'Health Visit',description:'Routine health monitoring.',structured_data:{encounter_type:'routine_monitoring'},verified_at:'2026-09-18T09:00:00Z'}];for(const record of records){const payload={patient_id:patientId,facility_id:phcId,practitioner_id:users.phc_worker,resource_type:'encounter',date_precision:'exact',source_type:'phc_entered',source_label:'Demo PHC',status:'verified',verified_by:users.phc_worker,...record};const {data,error}=await db.from('clinical_records').select('id').eq('patient_id',patientId).eq('title',record.title).maybeSingle();if(error)throw error;out=data?await db.from('clinical_records').update(payload).eq('id',data.id):await db.from('clinical_records').insert(payload);if(out.error)throw out.error}
console.log('Seeded one PHC, four authenticated demo accounts, one verified demo patient and two longitudinal records.');
